#+OPTIONS: H:4

* Introduction

An MCB-greedy method is a method to derive a minimal cycle base (MCB) from a candidate set of cycles of a graph.

The method uses a growing set of base cycles (more technically a monotoneous succession of partial cycle bases) with minimal length (based on a weight function) that gets extended with the respective next smallest linearly independent cycle not yet in the (partial) base.

For this the cycles are ordered by increasing weight, and enumerated. For every cycle encountered a linear independence check with the partial cycle base (based on the number field of interest) is performed, and if it is successful, the cycle is added to the partial cycle base, if not it is discarded.

* Remarks

Since the set of cycles is a matroid, the greedy algorithm yields the optimal result. Because of this and its simplicity, the method is very popular for MCB determination. 

A problem with the naïve implementation is the size of the candidate set; Using the full candidate set can yield to exponential running time, since the set of cycles can grow exponentially in the number of nodes / edges. The focus of this toolkit is to implement algorithms that generate polynomial candidate sets that contain a MCB in order to circumvent the problem.

Algorithms that are implemented are the [[Horton]] and the [[dePina]] algorithm.

* Algorithm
#+BEGIN_SRC latex
Input: Candidate set C of cycles in G = (V,E)
Output: MCB of G
\begin{equation}
1 Sort C by weight in ascending order C_{1},...,C_{k}
2 B \leftarrow \emptyset
3 for i=1 to k
4    if B \union \{C_{i}\} is linearly independent
5       B \leftarrow B \union \{C_{i}\}
\end{equation}
#+END_SRC
